TRAIN_PATH: "image_crawl/train_images"
TEST_PATH: "image_crawl/test_images"
# TEST_PATH: "D:/Downloads/VIRAC/VIRAC-OCR/image_crawl/sample/test_numbers_only"

RNN_HIDDEN_SIZE: 256
ACC_THRESHOLD: 0.87

BATCH_SIZE: 16
EPOCHS: 100

LR: 0.0003
WEIGHT_DECAY: 0.00001
CLIP_NORM: 5

EARLY_STOPPING_PATIENCE: 5
EARLY_STOPPING_MIN_DELTA: 0.001