TRAIN_PATH: "image_crawl/train_images"
TEST_PATH: "image_crawl/test_images"

BEST_MODEL_PATH: "/ocr/models/crnn/save/best.bin"
MAPPING_CHARACTER_PATH: "/ocr/dataset/mapping_char.json"

RNN_HIDDEN_SIZE: 256
ACC_THRESHOLD: 0.87

BATCH_SIZE: 32
EPOCHS: 100

LR: 0.0003
WEIGHT_DECAY: 0.00001
CLIP_NORM: 5

EARLY_STOPPING_PATIENCE: 5
EARLY_STOPPING_MIN_DELTA: 0.001